### ISSUE TITLE
When i try to node index.js it gives this error

### ISSUE THREAD

**Issue by R3XAS** [Lososiik/Token-Generator#1]
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'prompt-sync'
Require stack:
- C:\Users\MyName\OneDrive\Plocha\Token-Generator-main\Token-Generator-main\TokenGen\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at main (C:\UsersMyName\OneDrive\Plocha\Token-Generator-main\Token-Generator-main\TokenGen\index.js:10:14)
    at Object.<anonymous> (C:\Users\MyNameOneDrive\Plocha\Token-Generator-main\Token-Generator-main\TokenGen\index.js:252:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\MyName\\OneDrive\\Plocha\\Token-Generator-main\\Token-Generator-main\\TokenGen\\index.js'
  ]
}

Node.js v17.1.0

**Comment by ghost** [comment]
npm install prompt-sync

**Comment by eboujlal** [comment]
create a file called package.json
pase this code there : 
`{
  "name": "tokengen",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@cliqz/adblocker-puppeteer": "^1.23.2",
    "cross-fetch": "^3.1.4",
    "prompt-sync": "^4.2.0",
    "puppeteer-extra-plugin-recaptcha": "^3.5.0",
    "puppeteer-extra-plugin-stealth": "^2.9.0",
    "unique-names-generator": "^4.6.0"
  }
}
`

then run : npm install 

then run node index.js

**Comment by 002sans** [comment]
execute this:

`npm i @cliqz/adblocker-puppeteer cross-fetch prompt-sync puppeteer-extra-plugin-recaptcha puppeteer-extra-plugin-stealth unique-names-generator node-bash-title colors puppeteer-extra puppeteer-core puppeteer`
